import { createAdminClient } from "@/lib/supabase";
import type { Metadata } from "next";

interface Params { params: Promise<{ token: string }> }

type Reading = {
  type: "fire" | "earth" | "air" | "water";
  overview: string;
  majorLines: { title: string; content: string; meaning: string }[];
  mounts:     { name: string;  content: string; meaning: string }[];
  fingers:    { name: string;  content: string; meaning: string }[];
  signs:      { name: string;  content: string; meaning: string }[];
  career: string;
  love: string;
};

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { token } = await params;
  return {
    title: "Palm Reading — PalmWis",
    description: `A palm reading shared from PalmWis. Token: ${token}`,
    openGraph: {
      title: "My PalmWis Palm Reading",
      description: "See what the ancient art of palmistry reveals about this person.",
      url: `https://palmwis.app/reading/${token}`,
    },
  };
}

async function getReading(token: string): Promise<Reading | null> {
  const admin = createAdminClient();
  if (!admin) return null;

  const { data } = await admin
    .from("readings")
    .select("reading_data")
    .eq("share_token", token)
    .single();

  return (data as { reading_data: Reading } | null)?.reading_data ?? null;
}

const ELEMENT_META: Record<string, { emoji: string; color: string }> = {
  fire:  { emoji: "🔥", color: "#e94560" },
  earth: { emoji: "🌍", color: "#4ade80" },
  air:   { emoji: "💨", color: "#60a5fa" },
  water: { emoji: "💧", color: "#a78bfa" },
};

export default async function SharedReadingPage({ params }: Params) {
  const { token } = await params;
  const reading   = await getReading(token);

  if (!reading) {
    return (
      <main className="min-h-screen bg-mystical flex items-center justify-center px-6">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-6">🔮</div>
          <h1 className="font-decorative text-2xl text-highlight mb-4">Reading Not Found</h1>
          <p className="text-text-secondary mb-8">
            This reading link may have expired or Supabase is not yet configured.
          </p>
          <a href="/" className="btn-primary inline-block">Read My Own Palm</a>
        </div>
      </main>
    );
  }

  const meta = ELEMENT_META[reading.type] ?? ELEMENT_META.fire;

  return (
    <main className="min-h-screen bg-mystical py-20 px-6">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-gradient-to-b from-[#1a1a2e] to-transparent py-4 px-6">
        <div className="max-w-6xl mx-auto flex items-center gap-3">
          <span className="text-2xl">🖐️</span>
          <span className="font-decorative text-lg text-highlight">PalmWis</span>
        </div>
      </header>

      <div className="max-w-4xl mx-auto">
        {/* Banner */}
        <div className="text-center mb-12">
          <p className="text-text-secondary text-sm uppercase tracking-widest mb-4">Shared Palm Reading</p>
          <h1 className="font-decorative text-3xl md:text-4xl mb-4">
            A <span className="text-highlight capitalize">{reading.type} Element</span> Palm {meta.emoji}
          </h1>
          <p className="text-text-secondary max-w-xl mx-auto">
            This reading was generated by PalmWis — ancient palmistry wisdom powered by AI.
          </p>
        </div>

        {/* Overview */}
        <div className="card-mystical p-8 glow-subtle mb-6">
          <h2 className="font-decorative text-xl text-highlight mb-4">Personality Overview</h2>
          <p className="text-text-primary leading-relaxed">{reading.overview}</p>
        </div>

        {/* Major Lines */}
        <div className="card-mystical p-8 glow-subtle mb-6">
          <h2 className="font-decorative text-xl text-highlight mb-6">Major Palm Lines</h2>
          <div className="space-y-6">
            {reading.majorLines.map((line, i) => (
              <div key={i} className="border-l-4 border-[#e94560] pl-5 py-1">
                <h3 className="font-decorative text-base mb-2">{line.title} Line</h3>
                <p className="text-text-secondary text-sm leading-relaxed">{line.content}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Career & Love side-by-side */}
        <div className="grid md:grid-cols-2 gap-6 mb-12">
          <div className="card-mystical p-6 glow-subtle">
            <h2 className="font-decorative text-lg text-highlight mb-3">💼 Career</h2>
            <p className="text-text-secondary text-sm leading-relaxed">{reading.career}</p>
          </div>
          <div className="card-mystical p-6 glow-subtle">
            <h2 className="font-decorative text-lg text-highlight mb-3">❤️ Love</h2>
            <p className="text-text-secondary text-sm leading-relaxed">{reading.love}</p>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center">
          <p className="text-text-secondary mb-6">Curious what your palm reveals?</p>
          <a href="/" className="btn-primary inline-block text-lg">
            🖐️ Read My Palm — Free
          </a>
          <p className="text-xs text-text-secondary mt-4">
            For entertainment purposes only.
          </p>
        </div>
      </div>
    </main>
  );
}
